renamed color var, added new color var, changed bg color of drawer
GEOLYTIX/xyz pull request #1007
Opened 2023-11-16 13:15 UTC by eo-uk

Changed color palette, renamed the color-lighter variable to color-light-secondary and added another variation. Adjusted drawer background for a subtler background.

2023-11-16 15:51 UTC, dbauszus-glx approved these changes
Looks really good.

![image](https://github.com/GEOLYTIX/xyz/assets/22201617/7b477612-e882-4e6e-825e-3fffae5201b6)

2023-11-16 16:26 UTC, simon-leech requested changes
I much prefer the colour scheme but i've got a few thoughts - happy to be overruled though! 

1. The layer key is not apparent anymore.

![image](https://github.com/GEOLYTIX/xyz/assets/56163132/23a2604b-8609-4159-bf73-13ea2192948f)
![image](https://github.com/GEOLYTIX/xyz/assets/56163132/25dcc782-0791-4d03-a634-f32a80ea6a5e)

2. On the tabview, there's no longer a distinction between the tabview tabs and the information, which results in a vertical line that just ends and isn't super clear why. 
![image](https://github.com/GEOLYTIX/xyz/assets/56163132/e5ea3b77-586e-4778-acc1-b3765b191c7f)

![image](https://github.com/GEOLYTIX/xyz/assets/56163132/3db13e18-7a4a-4a62-9924-deb87c0d7144)
3. I don't think there's enough distinction between layer groups and individual layers. What about if layer groups have a bold header and layers were not bolded? 
![image](https://github.com/GEOLYTIX/xyz/assets/56163132/9b5e480b-6424-4aa6-b1a1-0d6c281f6fda)
![image](https://github.com/GEOLYTIX/xyz/assets/56163132/1993db02-9753-4f03-9eaf-1651c96479f1)

2023-11-17 12:37 UTC, RobAndrewHurst approved these changes
Looks good!

2023-11-17 16:34 UTC, simon-leech approved these changes
Thanks for addressing those bits I requested - this is looking brilliant now! much cleaner! 

I think this is fine to be merged once the tests all pass :)

2023-11-21 06:27 UTC, merged