Get scale_bar from locale
GEOLYTIX/xyz pull request #1068
Opened 2024-01-19 13:30 UTC by RobAndrewHurst

# Pull Request: Get `scale_bar` from locale 🌐📏

## Description
This pull request addresses the need to retrieve the `scale_bar` information from the locale. The changes aim to improve the localization of the scale bar in our application, enhancing the user experience by dynamically obtaining this information based on the user's locale.

## Changes Made
- Updated the `scale_bar` property in the default mapview to take the `scaleBar` property from the locales configuration. 🗺️🔄

## Testing Done
- [x] Tested against a workspace with multiple locales. One with 'imperial', 'Metric' and default (no scaleBar). ✔️🌍

2024-01-19 13:45 UTC, simon-leech requested changes
@RobAndrewHurst  Tested this and it works all good when you provide either `metric` or `imperial`. 
However, I tested this using a bogus term `test` and it fails. I wonder if this should be using a ternary or checking that the `scaleBar` value is either `metric` or `imperial` to guard against this. 

Please could you also update the Config Docs to explain this is a new option available? Thanks! 🙂

2024-01-19 14:32 UTC, RobAndrewHurst commented
@simon-leech I have made the changes!

2024-01-19 14:37 UTC, RobAndrewHurst commented
https://github.com/GEOLYTIX/xyz/wiki/Workspace-Configuration#scalebar

2024-01-19 14:40 UTC, AlexanderGeere approved these changes
Looks good on my end

2024-01-19 14:48 UTC, simon-leech approved these changes

2024-01-19 14:48 UTC, simon-leech commented
Thanks @RobAndrewHurst  - good with me!

2024-01-20 11:17 UTC, dbauszus-glx approved these changes
The scalebar line can be completely removed from the default view script.

The scalebar should not be there by default but only if configured in the locale.

Please check if you are happy with the changes.

2024-01-22 06:13 UTC, RobAndrewHurst commented
> The scalebar line can be completely removed from the default view script.
> 
> The scalebar should not be there by default but only if configured in the locale.
> 
> Please check if you are happy with the changes.

I still think we need a check if the config has a bogus unit provided. ie something not 'metric' or 'imperial'

2024-01-22 06:17 UTC, RobAndrewHurst commented
// Scalebar
  mapview.locale.scalebar && mapview.Map.addControl(new ol.control.ScaleLine({
    units: mapview.locale.scalebar === 'imperial' ? 'imperial' : 'metric',
  }))
  
@dbauszus-glx Also should `scalebar` not be `scaleBar` to keep in consistency with other properties that we use like `minZoom` and `maxZoom`?

2024-01-22 09:19 UTC, RobAndrewHurst commented
Ok cool! I am happy to change to ScaleLine.

I have already added in that check! 👍

2024-01-22 10:41 UTC, RobAndrewHurst commented
Updated Docs: https://github.com/GEOLYTIX/xyz/wiki/Workspace-Configuration#scaleline

2024-01-22 10:42 UTC, merged