provide string array argument as filter for ui.location.infoj(loc, [])
GEOLYTIX/xyz pull request #1083
Opened 2024-01-25 12:04 UTC by dbauszus-glx

If the infoj argument is provided as an array of strings a lookup for the entry with matching field will be attempted at the beginning of the iteration.

This does not backwards compatibility where the infoj argument is provided as an array of objects.

![image](https://github.com/GEOLYTIX/xyz/assets/22201617/c7aa37a9-a7e9-43a5-af29-198e6a04f321)

2024-01-26 08:55 UTC, simon-leech requested changes
Nice one @dbauszus-glx  - this is a clean solution! 

📃 Please could you write this up in the Docs? then I'll be happy to approve!

2024-01-26 09:43 UTC, dbauszus-glx commented
https://github.com/GEOLYTIX/xyz/wiki/MAPP.UI#infojlocation-infoj

2024-01-26 10:39 UTC, simon-leech approved these changes

2024-01-29 07:02 UTC, RobAndrewHurst approved these changes
Looks all good to me!

2024-01-29 09:21 UTC, merged