Move default btn methods to plugins
GEOLYTIX/xyz pull request #1088
Opened 2024-01-25 18:05 UTC by dbauszus-glx

locator, zoomToArea, and fullscreen behave exactly like plugins.

These 'default' plugins have been moved to the plugins module from the default view to clean up the default view.

Methods have been moved out of the <button> tag for better maintenance and linting.

2024-01-26 06:53 UTC, AlexanderGeere approved these changes
Tested in bugs and testing. Plugins still, code looks good

2024-01-26 08:49 UTC, simon-leech requested changes
This is working for me when using `locator: {}` as per this PR. 
❓However, this fails if I use the currently applied configuration prior to this PR of `locator: true`. As such, should this be referred to as a breaking change as it fails against current configuration? 
❓I also noted that you cannot hide this default plugins, i'm unsure if we should allow that but should this be possible to set `locator:false` for instance to remove it? 
📃 Please can you update the Config Docs to include this? For instance https://github.com/GEOLYTIX/xyz/wiki/Workspace-Configuration#locator this amending.

2024-01-26 09:22 UTC, dbauszus-glx commented
@simon-leech The plugin must accept a true flag. I did a commit for this. I agree that the default should be off. We should discuss what's the preferred setting for the default view.

2024-01-26 18:38 UTC, dbauszus-glx commented
@simon-leech can you re-review. The requested changes have been made.

2024-01-29 07:10 UTC, RobAndrewHurst commented
![image](https://github.com/GEOLYTIX/xyz/assets/43169158/d5cc9d78-45a6-4ed7-ac2c-c9718ef45c87)

@dbauszus-glx Is there a reason why there is a `plugin` param being passed to the function but isn't used?

2024-01-29 09:20 UTC, dbauszus-glx commented
@RobAndrewHurst No particular reason. It's just the default first param for these type of plugin methods. Could be null but doesn't hurt to know what the first param is.

2024-01-29 09:32 UTC, merged