If response from location-get is array, warn and return
GEOLYTIX/xyz pull request #1143
Opened 2024-02-15 15:37 UTC by simon-leech

If the location-get returns two locations, it indicates the qID is not actually unique. This PR just warns and returns if this occurs, so you can see why a location cannot be selected.

2024-02-15 17:49 UTC, dbauszus-glx requested changes
Can you make the checks as an else if to `!response` as these conditions would be mutually exclusive.

I'd also log the layer key and id to know which get query failed.

```js
if (!response) {

    console.warn('No data returned from location_get request.')
    return;

} else if (Array.isArray(response)) {

    console.warn('Location response returned more than one record. This is not allowed.')
    return;
}
```

2024-02-16 10:53 UTC, simon-leech commented
@dbauszus-glx Updated as per your comments - will mark this as ready for review 🙂

2024-02-16 11:48 UTC, dbauszus-glx requested changes
Can you add the if else to the location/decorate check as well.

2024-02-16 12:31 UTC, simon-leech commented
@dbauszus-glx How's that? Updated to use the same if else in both location, I return a warning and then return the response from the query.

2024-02-16 13:01 UTC, dbauszus-glx approved these changes
lovely.

2024-02-16 13:01 UTC, merged