Load sync plugins in sync before async plugins
GEOLYTIX/xyz pull request #1145
Opened 2024-02-15 19:06 UTC by dbauszus-glx

An array of plugin keys can be defined on the locale as `syncPlugins[]`

The default for this array if undefined is `['zoomBtn', 'admin', 'login']`

```js
locale.syncPlugins ??= ['zoomBtn', 'admin', 'login']
```

The plugins defined in this array will be executed in this order allowing us to configure the order in which buttons are added to the btnColumn element.

The zoomBtn, admin view link, and login/logout link have been converted into core plugins taking the elements out of the _default script and allowing us to control the order of all buttons.

2024-02-16 11:14 UTC, simon-leech requested changes
This is working well for me - I like it! 

Only change - please can you add it to the Config Docs?

2024-02-19 07:34 UTC, AlexanderGeere approved these changes
Looks good to me!

2024-02-19 09:54 UTC, dbauszus-glx commented
https://github.com/GEOLYTIX/xyz/wiki/Workspace-Configuration#syncplugins

2024-02-19 10:13 UTC, simon-leech approved these changes

2024-02-19 10:16 UTC, merged