Graduated zeroes error
GEOLYTIX/xyz pull request #1170
Opened 2024-03-05 07:58 UTC by AlexanderGeere

When the value on graduated theme is zero the style is never set, even if there is a zero category. 

This PR will set the style if one has not been set. 

Using `graduated_theme` in bugs_testing, the polygon over birmingham will be blank on main, and will fill with green correctly on this PR.

2024-03-05 16:23 UTC, dbauszus-glx requested changes
This doesn't seem right.

The three polygons have respective values of 0, 0.4, 0.6 and should display as the first three categories.

![image](https://github.com/GEOLYTIX/xyz/assets/22201617/dbf70b78-6255-4767-9a3d-5899c95e0179)

2024-03-05 18:08 UTC, dbauszus-glx commented
@AlexanderGeere Please check my last commit. I think this can be done with array methods.

```js
  if (!isNaN(catValue) && catValue !== null) {

    const isLassThan = cat => catValue <= cat.value;

    let index = theme.cat_arr.findIndex(isLassThan)

    let cat = theme.cat_arr.at(index)

    let catStyle = structuredClone(cat.style || cat)

    delete catStyle.label

    mapp.utils.merge(feature.style, catStyle)
  }
```

2024-03-06 07:14 UTC, AlexanderGeere commented
@dbauszus-glx  Works in the `graduated_theme` work space as well, looks a lot cleaner too. Nice!

2024-03-06 09:41 UTC, simon-leech approved these changes
Working for me too!

2024-03-06 11:17 UTC, merged