Circle change - geojson import
GEOLYTIX/xyz pull request #1233
Opened 2024-04-29 11:20 UTC by simon-leech

2024-05-03 15:04 UTC, dbauszus-glx requested changes
Can you break this down into two separate  PR? I am ok with the circle change, but believe the geojson import wants to be broken down. Can you create an issue with more details in regards to the specification for the geojson import?

2024-05-07 08:41 UTC, simon-leech commented
@dbauszus-glx  I have removed the geojson import from this PR - just got the circle changes now :)

2024-05-07 10:59 UTC, dbauszus-glx approved these changes

2024-05-07 11:01 UTC, dbauszus-glx commented
I added the hidePanel flag in order to maintain the current default behaviour. A radius and unit will always be assigned as default. The config object will just override the defaults. The dictionary label can be assigned in the defaults since the config will override. A spread operator should be used for this rather than object assignment.

2024-05-07 14:25 UTC, simon-leech reviewed
Added to the Config Docs here - 
https://github.com/GEOLYTIX/xyz/wiki/Workspace-Configuration#circle

But all working well for me! :)

2024-05-07 15:52 UTC, merged