Tabulaor 'Set' Headerfilter - no data from distinct query
GEOLYTIX/xyz pull request #1237
Opened 2024-04-29 15:10 UTC by AlexanderGeere

### What
Using the `set` `headerfilter` and `distinct` in the `headerFilterParams` would create an error, as the dropdown would attempt to iterate an empty list .

This PR should correct that by making a dropdown that has a no data message.

### Test Space
[`bugs_testing/dataviews_filter/workspace.json`](https://github.com/GEOLYTIX/xyz_resources/tree/bugs-testing/bugs_testing/dataviews_filter)

2024-04-29 17:42 UTC, dbauszus-glx commented
@AlexanderGeere can you add this to the tabulator plugin? ui.utils.tabulator will be removed from the mapp library as soon as the plugin is reviewed.

2024-04-30 08:43 UTC, AlexanderGeere commented
@dbauszus-glx Will do.

Changed it slightly so the dropdown works but just says no options.

2024-04-30 09:25 UTC, simon-leech approved these changes
All working well for me 👍

2024-04-30 10:46 UTC, dbauszus-glx requested changes
The method should not be dependent on the distinct flag but whether an options array is provided.

See filters for reference. https://github.com/GEOLYTIX/xyz/blob/main/lib/ui/layers/filters.mjs

If an array of options is defined than this should be used. If not, a query should be attempted to populate the options for the filter.

2024-05-02 14:34 UTC, dbauszus-glx approved these changes

2024-05-02 14:34 UTC, merged