infoj_order mode
GEOLYTIX/xyz pull request #1252
Opened 2024-05-10 13:17 UTC by dbauszus-glx

The infoj method has a second infoj_order argument. This argument can be an array of keys and entry objects.

layer.infoj entries will be filtered in the order of keys. It is checked whether the key matches the entry's key, field, query, or group key value.

The `key` key value is specifically used as an identifier for entries and serves no other purpose.

The infoj_order argument can be a mix of entry objects and keys. Entry object are directly spliced into the infoj array and don't require to be in the layer.infoj array.

The infoj_order can be defined as an array in the layer json. The infoj_order plugin will be retired in favour of this.

2024-05-13 09:18 UTC, RobAndrewHurst commented on lib/ui/locations/infoj.mjs
> +        entry.hasRan = true;
++

2024-05-13 10:35 UTC, cityremade commented
when including a dataview object in the order I see the following error: 
infoj.mjs:130 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'layer')
at line 130 in infoj.mjs: `entry.location.layer.queryparams || {}`
Entry in the order array doesn't inherit properties when they are referenced.

2024-05-13 10:44 UTC, RobAndrewHurst commented on lib/ui/locations/infoj.mjs
> +  if (!entry.title) return;
Noticed an issue here where if the entry had a title it would return. 

Was just missing the operator.

2024-05-13 11:24 UTC, KieronFerrey requested changes
Tested with @simon-leech - so throwing feedback here. 

1. Can we add `entry.type` to the options - as this enables plugins that add elements to the infoj to be ordered.
2. `entry.group` is not working correctly - this is possibly due to the fact that we aren't looping over the infoj and looking for every option that has that group - so it only returns one entry in each group. 
3. dataviews in the infoj don't seem to be ordering

2024-05-13 11:42 UTC, dbauszus-glx commented
@KieronFerrey group won't work since the values are not unique. tyoe won't work neither for the same reason. we need to remove the group key since sorting requires a unique identifier.

2024-05-13 13:31 UTC, simon-leech commented
I just pushed a commit to this PR after chatting to @RobAndrewHurst. 
This PR simply console warns the developer if a value provided in `infoj_order` array does not exist in the `location.infoj`. 
This is required to ensure that the developer added a unique identifier to plugin entries or other entries that may not be unique.

2024-05-13 14:00 UTC, AlexanderGeere approved these changes
Looks good to me, Can order dataviews as well!

2024-05-13 15:03 UTC, dbauszus-glx commented
I have removed group from the infoj_order lookup since this is by definition not unique.

2024-05-13 15:17 UTC, simon-leech commented
I just pushed a check on the mapview and locale - as is custom views called entries may not have a locale
``` js 
// Assign queryparams from layer, and locale.
  entry.queryparams = Object.assign(
    entry.queryparams || {},
    entry.location.layer.queryparams || {},
    entry.location.layer?.mapview?.locale?.queryparams || {})
```

2024-05-13 15:37 UTC, dbauszus-glx commented
@simon-leech Can you test whether this works using the spread operator?

![image](https://github.com/GEOLYTIX/xyz/assets/22201617/1affcc69-b3b2-4b90-aded-562aa0ffda33)

Aren't the locale queryparams already assigned to the layer somewhere else?

2024-05-13 15:41 UTC, simon-leech commented
@dbauszus-glx  Yeah all seems to be working for me :)

2024-05-13 15:41 UTC, simon-leech approved these changes

2024-05-13 15:48 UTC, KieronFerrey approved these changes
Looks good to me

2024-05-13 15:49 UTC, RobAndrewHurst approved these changes
Lets go!

2024-05-13 15:49 UTC, merged

2024-05-14 10:26 UTC, dbauszus-glx commented
https://github.com/GEOLYTIX/xyz/wiki/Workspace-Configuration#infoj_order