Review _user API mod
GEOLYTIX/xyz pull request #1264
Opened 2024-05-20 11:33 UTC by dbauszus-glx

The _user API methods should each individually check whether the ACL is provided. Whether usre.admin rights are required. Whether a user object / login is required.

The admin view method was pushed into it's own mod file `user/admin.js`

The `user/delete` API will now allow for a logged in user to remove themselves.

2024-06-04 08:05 UTC, AlexanderGeere approved these changes
Looks good to me

2024-06-04 11:52 UTC, RobAndrewHurst approved these changes

2024-06-04 12:14 UTC, AlexanderGeere approved these changes

2024-06-04 15:01 UTC, RobAndrewHurst commented
I am happy for this to be reviewed. @simon-leech Do you still want to write some tests for this? Or should I try give it a crack?

2024-06-04 18:51 UTC, simon-leech commented
@RobAndrewHurst  Happy for you to pick up the tests then I can review the PR and tests all in one go?

2024-06-05 06:56 UTC, RobAndrewHurst commented
Sure!

2024-06-05 07:18 UTC, RobAndrewHurst commented
> @RobAndrewHurst Happy for you to pick up the tests then I can review the PR and tests all in one go?

The main problem with testing these modules is that we can't test them via the CLI. We would want to write a login_test similar to the test_view to the run on deployed instances. This will then fully test the ACL. 

I don't see a point in mocking the ACL in the CLI. 

Let me know what you think?  

@AlexanderGeere @dbauszus-glx @simon-leech

2024-06-05 07:42 UTC, simon-leech commented
> > @RobAndrewHurst Happy for you to pick up the tests then I can review the PR and tests all in one go?
> 
> The main problem with testing these modules is that we can't test them via the CLI. We would want to write a login_test similar to the test_view to the run on deployed instances. This will then fully test the ACL.
> 
> I don't see a point in mocking the ACL in the CLI.
> 
> Let me know what you think?
> 
> @AlexanderGeere @dbauszus-glx @simon-leech



> > @RobAndrewHurst Happy for you to pick up the tests then I can review the PR and tests all in one go?
> 
> The main problem with testing these modules is that we can't test them via the CLI. We would want to write a login_test similar to the test_view to the run on deployed instances. This will then fully test the ACL.
> 
> I don't see a point in mocking the ACL in the CLI.
> 
> Let me know what you think?
> 
> @AlexanderGeere @dbauszus-glx @simon-leech

@RobAndrewHurst Agreed - sounds quite tricky to mock, maybe we can add a login_test view as a separate PR? Once this one is in?

2024-06-05 08:18 UTC, dbauszus-glx commented
Added 

/docs/module-_user.html

/docs/module-_utils_reqHost.html

2024-06-05 08:27 UTC, RobAndrewHurst commented
> @RobAndrewHurst Agreed - sounds quite tricky to mock, maybe we can add a login_test view as a separate PR? Once this one is in?

Sounds good!

2024-06-05 08:43 UTC, dbauszus-glx commented
Added /docs/module-_user_acl.html and /docs/module-_user_add.html

2024-06-06 15:33 UTC, dbauszus-glx commented
The auth module should use async verification of the token.

2024-06-07 12:45 UTC, dbauszus-glx commented
The login module should use the cookie module to assign a cookie.

The cookie module should use the fromACL module to get the user.

At the moment it is possible to recreate the cookie unless the user is blocked which is duplicate code.

2024-06-20 08:02 UTC, dbauszus-glx commented
The update method as called from the admin panel will now do the verification bits.

```js
  let verification_by_admin = ''
  if (req.params.field === 'verified' && req.params.value === true) {

    verification_by_admin = `
      , password = password_reset
      , password_reset = NULL
      , failedattempts = 0
      , verificationtoken = NULL
      , approved = true
      , approved_by = '${req.params.user.email}|${ISODate}'
    `
  }

  // Get user to update from ACL.
  const rows = await acl(`
    UPDATE acl_schema.acl_table
    SET
      ${req.params.field} = $2
      ${verification_by_admin}
      ${approved_by}
    WHERE lower(email) = lower($1);`,
    [email, req.params.value])

  if (rows instanceof Error) {
    return res.status(500).send('Failed to access ACL.')
  }
```

The verification can be called directly by an admin.

```
http://localhost:3000/api/user/update?email=dennis@mail.com&field=verified&value=true
```

2024-06-20 10:02 UTC, RobAndrewHurst requested changes
Can we force the users verification flag be set to false when they reset their passwords? So that when an admin user goes to reset their password via the verification flag they don't have to toggle it from true to false to true.

2024-06-20 10:09 UTC, dbauszus-glx commented
@RobAndrewHurst No, we cannot. Otherwise I could set your verification to false knowing your email address.

2024-06-20 10:19 UTC, RobAndrewHurst commented
We then need a way for Admin's to easily see who needs to be verified again

2024-06-20 12:14 UTC, dbauszus-glx commented
I added a column re_verification which is false if there user [record] has a verification token. If clicked on this the the verified true update query will be sent and the verified and approved columns will be toggled after successful update query.

2024-06-20 13:08 UTC, RobAndrewHurst commented
![image](https://github.com/GEOLYTIX/xyz/assets/43169158/75aee94e-d8ad-44a9-a4c7-65a2d5b93a49)

Resetting a users email (roberthurstsa@gmail.com) I don't see a green tick in the outstanding password reset column.

But after re-verifying the user through the admin panel, I then see a green tick for the user. Seems as if the logic needs to be reversed?

![image](https://github.com/GEOLYTIX/xyz/assets/43169158/1d80df37-db2a-434c-8c56-224631b66151)
^^ This is after re-verifying the user.

2024-06-20 13:13 UTC, dbauszus-glx commented
Green tick means that the user is fully verified. Happy for you to reverse the logic.

2024-06-20 13:39 UTC, RobAndrewHurst commented
> Green tick means that the user is fully verified. Happy for you to reverse the logic.

Ah ok! If you put it like that I am happy with it!

2024-06-20 15:15 UTC, RobAndrewHurst commented
![image](https://github.com/GEOLYTIX/xyz/assets/43169158/2aeb2bd0-0e9f-44b9-b50c-ecc4ec561088)

Should we change the message returned from this to maybe "Your session has been terminated. Please login again."

2024-06-20 15:18 UTC, RobAndrewHurst commented
![image](https://github.com/GEOLYTIX/xyz/assets/43169158/f6d15c10-6e58-429c-a816-f8f1bef72263)
 Maybe something like this.

2024-06-21 08:41 UTC, RobAndrewHurst requested changes
![image](https://github.com/GEOLYTIX/xyz/assets/43169158/11098f5b-4057-4076-aac7-eb010952cc72)

On vanilla email templates we don't see the host of the email that is being sent. In this case it should be `localhost:300`. I set the `ALIAS` in the .env and I don't see it coming through.

2024-06-21 09:15 UTC, dbauszus-glx commented
@RobAndrewHurst The issue with missing host should be resolved in last commit.

The register request get's short circuited in the api module since it doesn't have user auth by definition.

Hence the reqHost util is required in the register module itself.

2024-06-21 10:07 UTC, RobAndrewHurst approved these changes
I have run through the ACL process. Looks all good!

2024-06-21 15:27 UTC, simon-leech reviewed
I'm happy with this too, seems to be working from my testing!

2024-06-21 15:28 UTC, simon-leech commented
It doesn't seem to want me to mark it as approved though idk why 😂

2024-06-24 08:31 UTC, simon-leech approved these changes

2024-06-24 11:06 UTC, dbauszus-glx commented
The register new user method will no longer create a SQL Select statement but provide a values array to the ACL mod.

```js
  const USER = {
    email: req.body.email,
    password: req.body.password,
    password_reset: req.body.password,
    language: req.body.language,
    verificationtoken: req.body.verificationtoken,
    access_log: [`${date}@${req.ips && req.ips.pop() || req.ip}`]
  }

  if (process.env.APPROVAL_EXPIRY) {
    INSERTS.push('expires_on')
    VALUES.push(expiry_date)
    USER['expires_on'] = expiry_date
  }

  // Create new user account
  const rows = await acl(`
    INSERT INTO acl_schema.acl_table (${Object.keys(USER).join(',')})
    VALUES (${Object.keys(USER).map((NULL,i) => `\$${i+1}`)})`,
    Object.values(USER))
```

The user admin script will use tabulator 6.2 imports from unpkg.

The user admin cell toggle script will apply the verified logic for verified column clicks as well as re-verification.

2024-06-24 12:40 UTC, RobAndrewHurst approved these changes
**Nice one** all works for me

2024-06-24 12:41 UTC, merged