Admin view
GEOLYTIX/xyz pull request #1359
Opened 2024-07-02 09:45 UTC by cityremade

Admin view redesign including mobile usability;

2024-07-05 13:57 UTC, dbauszus-glx commented
The optional method param must end with a question mark. There must only be one get and one post application definition for the same endpoint.

```js
app.get(`${process.env.DIR||''}/api/user/:method?`, api)

app.post(`${process.env.DIR||''}/api/user/:method?`, express.json({limit: '5mb'}), api)
```

The update method will now receive a req.body. I changed the put to update in the user view script.

![image](https://github.com/GEOLYTIX/xyz/assets/22201617/258c559c-9672-4cda-914d-de88b4bdaffd)

The user add method should be extended to also check for a req.body.

The checks for the params.user must be first. The params user is the admin user.

![image](https://github.com/GEOLYTIX/xyz/assets/22201617/359eb6a0-35cd-4668-9cce-90775c6be5d7)

2024-07-10 10:14 UTC, simon-leech commented
Various list of changes from me / Admins here :)

They were big fans of the changes so well done @cityremade ! 🥳

**Main View**
1. Capitalise Email in the table header
2. Below Show blocked accounts checkbox add text saying 'Click on an email in the table to make changes to the users permissions and roles'
3. Make New Orange instead of red
4. Make Awaiting Verification red - as it requires fixing

**Form** 
1. Capitalise Email 
2. Update tooltips on checkboxes - should all start 
'Check the box to verify a user' 
'Check the box to re-verify after password reset' 
'Check the box to approve a user' 
'Check the box to make user an administrator'
'Check the box to allow the user API privileges'
'Check the box to block the user' 
3. Option to pass in text about what User Roles are (perhaps an eye that expands).
4. 'Account Expiry' instead of 'Account expires on'

2024-07-10 10:36 UTC, jfitzpatrick17 commented
Looks really good @cityremade! 👏

One thought I had...should we make the Status column sortable (by clicking on the column header) so it's easier for the user to find all of the accounts which require action?

2024-07-11 14:00 UTC, AlexanderGeere requested changes
When i click cancel the changes get saved. I think `save` and `cancel` are overlapping maybe.

2024-07-11 18:09 UTC, cityremade commented
In order to use role description add roles object in the workspace:
`"roles": {
    "this role": {
      "label": "This is a label that explains what this role does"
    }
  }`

2024-07-12 09:26 UTC, simon-leech requested changes
Few things from me 

❌ With a short user table you end up with a scrollbar that's unrequired. Can we set it to only appear if required? 

![image](https://github.com/user-attachments/assets/e15a57d0-7943-49cc-9cdb-88329be3c6a4)

❓ On mobile the checkbox tooltips are not accessible. Wonder if we should put them one a row one by one with the checkbox and explanation side-by-side? 

❓ Do we need the dialog to say changes have been saved ? As when you click Save the form is closed anyway? 

🌍 Can we convert all the hard-coded english strings to a dictionary object? So we can support multiple languages? (It should use the logged in users language for the language of the administration panel) 

🎨 Could we maybe style the role options slightly different as they are quite hard to distinguish from the underlying form due to similar colour?
![image](https://github.com/user-attachments/assets/6a8c5b50-3e18-4780-baa8-4bd3e7dd8152)

❓Can we add a little padding before the i 
![image](https://github.com/user-attachments/assets/c6477958-b17d-4ed2-bb17-da822a786b49)

❓ Can we put each Role text and label as a separate bullet point so they are laid out well? For example below my roles are APAC East and Global, so they should be on separate bullet points and separate lines?
![image](https://github.com/user-attachments/assets/b5da0aed-53ea-4ad6-887c-b78ff130f4a6)

2024-07-12 09:26 UTC, simon-leech commented on mod/user/add.js
Why does this have a if statement for `req.body` that just `console.logs` ?

2024-07-12 09:26 UTC, simon-leech commented on mod/user/update.js
Why does this have a if statement for `req.body` that just `console.logs` ?

2024-07-12 09:33 UTC, dbauszus-glx commented on mod/user/add.js
The user put method should be merged with the user add method. There should not be two methods doing the same but slightly different. I added the console.log() to show the request body and that a separate module is not required.

2024-07-12 09:36 UTC, dbauszus-glx requested changes
The `user/put` and `user/add` modules should be merged as they do the same.

2024-07-12 11:56 UTC, cityremade commented
> The `user/put` and `user/add` modules should be merged as they do the same.

create and update should be separate. I'd rather merge put + update;

2024-07-12 12:48 UTC, RobAndrewHurst requested changes
Can we add the ability to sort by the columns in the table? 

Clicking on them does nothing

2024-07-12 14:29 UTC, cityremade commented
> Can we add the ability to sort by the columns in the table?
> 
> Clicking on them does nothing

nope. Sorting was deliberately removed - now search filters are in place.

2024-07-12 14:44 UTC, RobAndrewHurst commented
> > Can we add the ability to sort by the columns in the table?
> > Clicking on them does nothing
> 
> nope. Sorting was deliberately removed - now search filters are in place.

Why were they removed?

2024-07-12 14:46 UTC, jfitzpatrick17 commented
> > > Can we add the ability to sort by the columns in the table?
> > > Clicking on them does nothing
> > 
> > 
> > nope. Sorting was deliberately removed - now search filters are in place.
> 
> Why were they removed?

I also asked for this. I use this all the time in the current console to sort by when people have last logged in...

2024-07-12 14:47 UTC, simon-leech commented
I'm getting error on save 
error: column "re_verification" of relation "users" does not exist as i think it should be looking at the verified column when you re_verification?

Also i noticed on mobile the dialog text doesn't wrap so it gets lost off the page. 
![image](https://github.com/user-attachments/assets/a03cc0fa-01d3-4512-ab71-901d0c158947)

2024-07-12 14:50 UTC, RobAndrewHurst commented
Me thinks this is using an ACL table that is missing a column? It would have been part of #1264

2024-07-12 14:52 UTC, simon-leech commented
> Me thinks this is using an ACL table that is missing a column? It would have been part of #1264

Not the case - in #1264  it had a conditional on the field. We need to put this back in as its uses the verified field on the db.

![image](https://github.com/user-attachments/assets/f12aaf47-3272-4308-ae3c-72dcd5fdc304)

2024-07-12 14:52 UTC, RobAndrewHurst commented
We don't want to do these tests on private ACL's but on public ones. @cityremade Can you redeploy using the ACL on our neon instance?

2024-07-12 14:53 UTC, RobAndrewHurst requested changes
Issues outstanding, it also seems we need a spec of what has been done in the PR, and test out each individual UX.

2024-07-12 14:59 UTC, RobAndrewHurst commented
> > Me thinks this is using an ACL table that is missing a column? It would have been part of #1264
> 
> Not the case - in #1264 it had a conditional on the field before storing to the db. We need to put this back in as its uses the verified field on the db -there is no reverfication_field.
> 
> ![image](https://private-user-images.githubusercontent.com/56163132/348303117-f12aaf47-3272-4308-ae3c-72dcd5fdc304.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3OTY2MjUsIm5iZiI6MTcyMDc5NjMyNSwicGF0aCI6Ii81NjE2MzEzMi8zNDgzMDMxMTctZjEyYWFmNDctMzI3Mi00MzA4LWFlM2MtNzJkY2Q1ZmRjMzA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDE0NTg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MTE2YTIxMGUwNTJjYWQxMDE2ODEyOTIxN2NiZjQ4NWY1ZWMzYTJiN2M0NDIwMDM4ZWE2YzE0YWQ1Nzc4ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vE7HGqFlMNgkmENBimkiK1tcyUuduxzuIoVwyC9vz4c)

Nice pick up! :)

2024-07-24 10:14 UTC, dbauszus-glx requested changes
The current admin view as well as any custom admin view must still work.

The updated admin view should be taken out of this PR and provided as a public view for testing the updated user API modules.

We can then test the user API modules on the current view and against the custom view.

The views can be swapped in the future in a separate PR.

2024-07-26 11:30 UTC, closed without merging

2024-07-26 11:30 UTC, cityremade commented
Closing as the task has been split into 2 separate changes. This branch is no longer needed.