infoj_skip in layer decorator
GEOLYTIX/xyz pull request #1366
Opened 2024-07-08 15:42 UTC by dbauszus-glx

The infoj_skip array should only processed once when the layer is decorated.

Creating a new Set on each iteration of multiple entry object properties on each iteration of every entry in the infoj is incredibly resource wasteful.

The uncommented negated array check in the filters panel lookup is hard to understand test or maintain.

It is much easier to set a flag in the infoj_array based on inclusion in the infoj_array which must a be an array and therefore supports the [array.includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) method.

2024-07-09 18:43 UTC, RobAndrewHurst commented
<img width="1784" alt="image" src="https://github.com/GEOLYTIX/xyz/assets/43169158/37739673-b7b5-40c9-81f2-2c0e3f912d9a">

When skipping an entry I am getting an error.

You can replicate this by using the workspace in infoj/infoj_skip.json

2024-07-09 18:44 UTC, RobAndrewHurst requested changes
See comment above.

2024-07-10 07:55 UTC, dbauszus-glx commented
I must have accidentally deleted the tip of the arrow function. @RobAndrewHurst can you test again.

2024-07-10 12:11 UTC, RobAndrewHurst approved these changes

2024-07-10 13:11 UTC, simon-leech approved these changes

2024-07-10 17:15 UTC, merged