Allow for array updates with text entry arraySeparator
GEOLYTIX/xyz pull request #1385
Opened 2024-07-18 08:43 UTC by dbauszus-glx

In order to set and update an array type database field the arraySeparator edit property is introduced in this PR.

```js
"edit": {
  "arraySeparator": ","
}
```

The `onInput` method of the text input element will use the arraySeparator character to split a provided target element string value into an array provided as newValue property value to the entry.

[Screencast from 18-07-24 09:00:39.webm](https://github.com/user-attachments/assets/539543de-94a6-40a2-8351-218e33da7bf1)

2024-07-18 08:47 UTC, RobAndrewHurst commented
Interesting!

2024-07-24 07:56 UTC, simon-leech requested changes
On testing this on a layer with a display true layer dataview - when you press save on a location you hit an edit from here. 

![image](https://github.com/user-attachments/assets/aec5af46-b24c-4342-885d-c7c6dea49f6c)


The actual arraySeparator flag is working as expected though - a nice feature :)

2024-07-25 09:06 UTC, dbauszus-glx commented
@simon-leech The bug is unrelated to this feature and addressed in this PR. https://github.com/GEOLYTIX/xyz/pull/1395

2024-07-25 17:20 UTC, simon-leech approved these changes

2024-07-26 13:34 UTC, AlexanderGeere approved these changes

2024-07-26 15:01 UTC, merged