entry type:layer to replace mvt_clone
GEOLYTIX/xyz pull request #1386
Opened 2024-07-18 17:44 UTC by dbauszus-glx

2024-10-11 17:28 UTC, dbauszus-glx commented
The featureSet and lookupFeature logic has now been merged in the showLayer method of the layer entry and the featureProperties method of the featureStyle module.

The layer decoration in the layer entry has been moved to the decorateLayer method in the layer entry module.

A changeEnd event listener for zoom restricted layer has been added to the  decorateLayer to disable the entry checkbox if the entry layer is out of range.

https://github.com/GEOLYTIX/xyz/issues/1543 must be completed before the layer entry PR can be resolved.

2024-10-18 08:58 UTC, RobAndrewHurst commented on lib/ui/locations/entries/layer.mjs
> +  console.log(entry)
This should be removed!
```suggestion
  console.log(entry)
```

2024-10-18 08:58 UTC, RobAndrewHurst commented on lib/ui/locations/entries/layer.mjs
> +  console.log(entry)
This should be removed! 
```suggestion
```

2024-10-18 13:27 UTC, RobAndrewHurst commented
a4edfd93aaf4288ee3220343281cad8f58107fd0

```js
// Request the location fields from layer json & id.
  const response = await mapp.utils.xhr(`${mapp.host}/api/query?` + mapp.utils.paramString({
    template: location.getTemplate,
    locale: location.locale,
    layer: location.layer.key,
    table: location.table,
    id: location.id,
  }));
```

I noticed that the `layer` property on the `getInfoj()` method in the lib/location/get.mjs module will be set by a unique layer name from the layer entry, which wouldn't work. I am going to add in the `location.layer.Key` as a first option when querying the data.

```js
  // Request the location fields from layer json & id.
  const response = await mapp.utils.xhr(`${mapp.host}/api/query?` + mapp.utils.paramString({
    template: location.getTemplate,
    locale: location.locale,
    layer: location.layer.Key || location.layer.key,
    table: location.table,
    id: location.id,
  }));
```

2024-10-22 11:27 UTC, simon-leech requested changes
An `infoj` `entry` `layer` with multiple thematics is not working correctly. 

the theme is swapped correctly on the mapview, but the legend is not updated and the legend styling is just lost. 


To swap an `mvt_clone` to type `layer` - is it supposed to be as simple as just changing the type? 
I did this but I crash here 
![image](https://github.com/user-attachments/assets/19d60606-9963-4672-a079-a63205ba4c09)

2024-10-22 12:20 UTC, dbauszus-glx commented
> An `infoj` `entry` `layer` with multiple thematics is not working correctly.
> 
> the theme is swapped correctly on the mapview, but the legend is not updated and the legend styling is just lost.
> 
> To swap an `mvt_clone` to type `layer` - is it supposed to be as simple as just changing the type? I did this but I crash here on layer.style.theme.title ![image](https://private-user-images.githubusercontent.com/56163132/378827716-19d60606-9963-4672-a079-a63205ba4c09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTkzMDMsIm5iZiI6MTcyOTU5OTAwMywicGF0aCI6Ii81NjE2MzEzMi8zNzg4Mjc3MTYtMTlkNjA2MDYtOTk2My00NjcyLWEwNzktYTYzMjA1YmE0YzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDEyMTAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiOTk4NTQzY2Y3NTJiYTJmYzIzMGQ1MjMzYmU3MjcyYjU1YzE0YjgxYWM4Y2UzMWE2YWM4MDM3NGE3MDhlMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-s2M2yogRho1PF4x0c3imeDrf8Y6oMzyvI5HaHLO2TI)

Yes, the layer entry type will replace the mvt_clone entry type method.

2024-10-22 12:47 UTC, dbauszus-glx commented
https://github.com/GEOLYTIX/xyz/pull/1386/commits/b81cd41c394527d5355cb572246fb3b01aadac0f

@simon-leech The layer entry method will now assign the layer.style.panel and the dropdown callback will replace the children in the style.panel.

2024-10-22 16:52 UTC, simon-leech approved these changes
Working for me - tested using mvt_clone and layer method and both are working for me :)

2024-10-22 16:56 UTC, RobAndrewHurst approved these changes

2024-10-22 16:56 UTC, merged