Update vector_layer.mjs
GEOLYTIX/xyz pull request #1391
Opened 2024-07-23 15:39 UTC by simon-leech

# Pull Request Template

## Description

An `infoj` `entry` of `type: vector_layer` would previously be assigned the `location.style` if not provided. 
However following `styleParser` and the need for `style.default.icon` the if statement in the code was not hit.

## Type of Change
Please delete options that are not relevant, and select all options that apply. 

- ✅ Bug fix (non-breaking change which fixes an issue)

## How have you tested this? 
Tested locally on my machine.

## Testing Checklist 
Please delete options that are not relevant, and select all options that apply. 

- ✅ Existing Tests still pass
- ✅ New Tests Added
- ✅ Ran locally on my machine

## Code Quality Checklist
Please delete options that are not relevant, and select all options that apply. 

- ✅ My code follows the guidelines of XYZ
- ✅ My code has been commented
- ✅ Documentation has been updated
- ✅ New and existing unit tests pass locally with my changes
- ✅ Main has been merged into this PR

2024-07-24 17:23 UTC, dbauszus-glx requested changes
It may be completely valid to have a default style for vector_layer without icons.

I have test vector layer for isolines which don't have an icon style. There should be no warning since the default style is correct.

```js
  if (entry.style.default && !entry.style.default.icon) {

    // Should be default.icon 
    entry.style.default.icon ??= { 'icon': entry.style.default };
    console.warn(`${entry.label}: Default style should be default.icon.`)
  };
```

The data-id assignment for the checkbox key must be reversed. It is possible that the key is a number and data-id cannot start with a number.

![image](https://github.com/user-attachments/assets/e3741236-31ab-432c-b31f-59d518f4d828)

I haven't got further in testing as the test workspace crashed out for me at this stage.

I removed the `@example` this should be reserved for future use where we have actual example script which may be executed. A json or js script block should just be trippled tagged.

I formatted the script block to remove lots of leading spaces/tabs.

The function description should follow the `@description` tag. The `@function` tag should always be first for a function.

This is for the vscode highlight to look like so:

![image](https://github.com/user-attachments/assets/7fc3d881-56c8-4bce-9a3d-278b10565fcb)

The entry param should be defined as infoj-entry typedef.

https://github.com/GEOLYTIX/xyz/pull/1391/commits/924d4620905a66c8112c3d13d389ce15fff3027d

2024-07-25 07:49 UTC, simon-leech commented
@dbauszus-glx  I've swapped the `data_id` around so it begins with `checkbox-` now. 
I've also added a check on `style.default` and `style.default.icon` separately for the `location.Style` merging

2024-07-25 12:50 UTC, dbauszus-glx approved these changes
This works for me on the test workspace and on the isolines test workspace.

Though I am aware that there are other issues which need to be addressed in the future.

2024-07-26 13:52 UTC, AlexanderGeere approved these changes

2024-07-26 15:01 UTC, merged