Add icon_scaling to featureStyle methods.
GEOLYTIX/xyz pull request #1414
Opened 2024-08-12 17:16 UTC by dbauszus-glx

A property is required for scaling feature style icons.

The feature fields params array was previously created in three different locations.

The method was now push as fieldsArray to the featureFields module.

The icon_scaling.field will be added to fields requested for feature properties.

The icon_scaling itself must happen separately from the cluster scaling. It must be possible to scale any type of icon.

2024-08-16 14:59 UTC, simon-leech requested changes
I think this should work whereby we get the `min` and `max` of the field using the `minmax` template and then scale the value proportionally across the range of min to max. 

Currently i'm testing on a field that holds values that go up to millions (a sales field) - and the icons take up the whole world in the mapview, its not usable. 

I even tried put the maxFactor down to 0.000000000000000000000000001 but still they are too large to use!

2024-08-16 15:08 UTC, dbauszus-glx commented
@simon-leech We can lookup the max value if undefined but it must be possible to manually define this.

Imagine a datasets of [10,30,50] which are percent. In order to set these to be scaled percent it must be possible define 100 as the maxFactor for scaling.

2024-08-19 13:48 UTC, simon-leech commented
@dbauszus-glx  Another question - If i leave off the `avgCluster` flag, the cluster icons are gigantic as I guess they are summed values for all features within them? 
Is it possible to say you only want to apply the icon scaling to the individual feature icon and ignore cluster features?

2024-08-19 14:11 UTC, dbauszus-glx commented
> @dbauszus-glx Another question - If i leave off the `avgCluster` flag, the cluster icons are gigantic as I guess they are summed values for all features within them? Is it possible to say you only want to apply the icon scaling to the individual feature icon and ignore cluster features?

That's correct. Sum is the default. avgCluster calculates the average. I can make scaling of cluster optional.

2024-08-19 14:12 UTC, simon-leech commented
> > @dbauszus-glx Another question - If i leave off the `avgCluster` flag, the cluster icons are gigantic as I guess they are summed values for all features within them? Is it possible to say you only want to apply the icon scaling to the individual feature icon and ignore cluster features?
> 
> That's correct. Sum is the default. avgCluster calculates the average. I can make scaling of cluster optional.

Yeah I think that would be a good feature, 
maybe we could have 
"cluster": "average" or "cluster": "sum" or if you don't include it then it just doesn't scale the cluster?

2024-08-21 13:08 UTC, dbauszus-glx commented
@simon-leech 

I've added the calculation for the maxFactor in the revised `featureFields` module methods.

Cluster feature scaling is now optional and can be sum [default] or average.

I've updated the initital comment with details.

2024-08-22 13:57 UTC, RobAndrewHurst reviewed
Quick question what is the use case for defning the maxfactor in the style? Instead of just having it calculated?

2024-08-22 14:01 UTC, RobAndrewHurst approved these changes
Actually I can see it being used for things like percentages, indexes etc.

2024-08-22 14:17 UTC, RobAndrewHurst approved these changes
Nice! I am happy with this!

And i have a good idea of how to write tests for this!

2024-08-23 11:23 UTC, AlexanderGeere approved these changes
Looks good to me

2024-08-23 11:32 UTC, simon-leech requested changes
Review ongoing - please don't merge yet

2024-08-27 10:25 UTC, dbauszus-glx commented
The icon_scaling.max will always be calculated in the featureFields process method.

The icon_scaling.scaleFactor will always be used if implicit.

The factor to calculate the scaling will be the max if not implicit as scaleFactor. A fallback of 1 is taken if neither is not falsy to prevent an item from not being displayed at all.

2024-08-27 17:07 UTC, simon-leech approved these changes
I'm happy with how this is working now - looking good! 
Thanks @dbauszus-glx  👍

2024-08-28 05:25 UTC, RobAndrewHurst approved these changes
I am happy for this to go in. 

The tests needs a set of eyes though 👀

2024-08-28 05:25 UTC, RobAndrewHurst commented on tests/lib/layer/featureStyle.test.mjs
> +        await codi.it('featureStyle: Icon Scaling', async () => {
Please can someone review this test and help me with the assertion!

2024-08-28 08:36 UTC, dbauszus-glx commented
I updated the featureFormats test to test for style.icon_scaling on wkt format with a minimum setup.

```js
    codi.it('Test style.icon_scaling for WKT features', () => {

      const mapview = {
        "srid": "3857"
      }

      const layer = {
        "format": "wkt",
        "params": {
          "fields": [
            "size"
          ]
        },
        "style": {
          "icon_scaling": {
            "field": "size"
          }
        },
        mapview
      }

      const features = [
        [
          1,
          "POINT(-14400 6710852)",
          null
        ],
        [
          2,
          "POINT(-14920 6711046)",
          10
        ],
        [
          3,
          "POINT(-15322 6710796)",
          15
        ]
      ]

      mapp.layer.featureFormats[layer.format](layer, features)

      return layer.style.icon_scaling.max === 15
    });
```

I am not sure about the featureStyle test structure. There should be test for the layer.featureStyle methods but these should check whether a feature and layer passed to the feature style method get the JSON style assigned which we would expect the feature to get assigned. 

Tests shouldn't involve cloud databases but should work with controlled test data. The current featureStyle.test may fail because the database cannot be accessed. 300 may not be the max field value. The location.update could fail. All these methods should be tested individually.

2024-08-28 08:49 UTC, simon-leech commented
Liking that test @dbauszus-glx  - I have just reset the featureStyle test to "TO DO" and removed the content. As the test you pushed is testing the same thing as in this PR.

2024-08-29 04:44 UTC, RobAndrewHurst submitted a review, later dismissed
The featureFormats tests for the icon scaling needs to make an assertion otherwise the test will pass every time.

2024-08-29 04:51 UTC, RobAndrewHurst commented
I have updated the test so that it now asserts the value with the codi library. There are still issues with checking that the max is recalculated when the data set is updated, which is what that previous test that was removed was doing.

2024-08-29 13:11 UTC, RobAndrewHurst approved these changes

2024-08-29 13:11 UTC, merged