mapp.ui.elements.alert/ confirm methods
GEOLYTIX/xyz pull request #1484
Opened 2024-09-18 13:31 UTC by cityremade

mapp.ui.elements.alert
mapp.ui.elements.confirm

This is alert / confirm elements to display information to the user.

Uses the existing ui.elements.dialog.

2 parameters added to the dialog:

closeOnClick - when set to true the dialog closes when the document is clicked anywhere over the backdrop.
onClose - callback function to execute when dialog fires a close event.

```js
mapp.ui.elements.alert({
   text: "Drivetimes have been created."
})

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208407306090518

2024-09-18 13:52 UTC, RobAndrewHurst commented on lib/ui/elements/alert.mjs
> +    const css = `
We are going to want to move this css into the bundled css sheet

2024-09-23 10:00 UTC, dbauszus-glx requested changes
This should make use of the mapp.ui.elements.dialog() method to create the dialog itself.

2024-09-23 12:55 UTC, cityremade commented
Changes made:

alert is now a ui.elements.dialog.

2 parameters added to the dialog:

closeOnClick - when set to true the dialog closes when the document is clicked anywhere over the backdrop.
onClose - callback function to execute when dialog fires a close event.

Both documented in the dialog module.

2024-09-23 15:51 UTC, dbauszus-glx requested changes
The confirm dialog in /ui/locations/view breaks with mapp.ui.elements not being a function.

![image](https://github.com/user-attachments/assets/eb0f940a-b435-4514-a11e-a4a8b863c7a1)

This can be tested by removing a location with outstanding edits.

`.mapp-says` should be replaced with a semantic class like `.alert-confirm`

The jsdoc return for function that return a promise must be promise with the text explaining how the promise resolves.

2024-09-23 16:15 UTC, simon-leech requested changes

2024-09-23 16:15 UTC, simon-leech commented on lib/ui/locations/view.mjs
On line 271- should this `&&confirm` also use the `mapp.ui.elements.confirm` method?

2024-09-25 07:08 UTC, simon-leech requested changes
Review in progress - no commits please

2024-09-25 07:37 UTC, simon-leech approved these changes
A few changes from me but I'm very happy with this, like it a lot! 

1. I moved the Ok and Cancel Buttons in the Confirm method so Ok is first as this matches the rest of the UI - e.g. see the unsaved changes dialog, we always have Ok on the left. 
![image](https://github.com/user-attachments/assets/3115db0a-1a81-4b1d-9d39-e0dfed3977d5)
![image](https://github.com/user-attachments/assets/18891a72-f25d-408a-8761-50987d905d4e)
2. I turned the text 'Confirm' and 'Information', the default titles when not provided into dictionary terms instead of being hardcoded, so they can be translated in the future. 
3. I wrote a series of tests for both Alert and Confirm methods that test for passing in Title and Text, and also passing in no params. They check for the presence of the correct content and buttons. 
![image](https://github.com/user-attachments/assets/48740668-1c90-4c56-af41-a9709b275411)

2024-09-25 17:10 UTC, RobAndrewHurst commented
I have added in a test for the dialog ui element to test the close functionality. And I noticed after invoking the close that the dialog can still be found in the DOM. I am not too sure if this is something todo with dialogs, or if we are not closing correctly.

2024-09-25 17:10 UTC, RobAndrewHurst requested changes
See comment above.

2024-09-26 08:54 UTC, cityremade commented
ui.elements.dialog has onClose callback where closed dialog can be removed if needed.
Removing the element will not be a case at all times.

2024-09-26 10:07 UTC, dbauszus-glx requested changes
The dialog element method decorates the params argument.

```js
const dialog = {
  content: 'foo'
}

// dialog becomes the decorated dialog object with the dialog.node being the dialog node element.
mapp.ui.elements.dialog(dialog)
```

The dialog element method should return the decorated dialog.

```js
// dialog becomes the decorated dialog with the dialog.node being the dialog node element.
const dialog = mapp.ui.elements.dialog({
  content: 'foo'
})
```

The `dialog.close()` method should call the dialog element close method as well as remove the element.

```js
dialog.close = ()=>{
  dialog.node.close()
  dialog.node.remove()
}
```

2024-09-26 17:36 UTC, dbauszus-glx requested changes
The confirm dialog closes when I click on the header. This shouldn't happen.

The closeBtn shouldn't be there if it shouldn't be there. Regardless whether the styling set's the button to the same colour.

2024-09-27 14:31 UTC, dbauszus-glx commented
We try to avoid negating flags. I removed the hideCloseBtn reference. Default will be no close button. If the closeBtn is defined, ie true then the property will be mutated to a html fragment. No web api node needed here. Also no tertiary statement needed.

https://github.com/GEOLYTIX/xyz/pull/1484/commits/7bb0b498987c52ee512dae61c9cdd8dc926bb12e

2024-09-27 14:42 UTC, dbauszus-glx commented
There was a lot of unnecessary stopPropagation. There must not be a click event on the dialog element. Also the dialog must not close when clicked anywhere. That defeats the logic of a confirm dialog. A confirm dialog should be boolean. E.g. Ok=true, Cancel=false. There is no tertiary whatever/close state.

There was a lot of close onClose closeDialog action. This has been streamlined.

The closeDialog method calls the onClose event method.

The dialog.close is closeDialog method.

dialog.clkoseBtn calls closeDialog method.

dialog onclose event calls closeDialog method.

there shouldn't be any stopPropagation required.

![image](https://github.com/user-attachments/assets/58394627-d166-4ce3-aa86-bc10478c5f7e)

2024-09-27 14:42 UTC, dbauszus-glx approved these changes
This is now working for me as expected. Please see comments.

2024-09-27 16:40 UTC, RobAndrewHurst approved these changes

2024-09-27 16:40 UTC, merged