CSS For Infoj Headers Update
GEOLYTIX/xyz pull request #1521
Opened 2024-10-02 09:08 UTC by simon-leech

# Pull Request Template

## Description

We have been told before that the group distinction compared to the rest of the Infoj is not clear enough.
The motivation for this PR is to address that, helping to break up the white in the infoj by using the primary colour as the header background. 

## Type of Change
Please delete options that are not relevant, and select all options that apply. 

- ✅ CSS

## How have you tested this? 
Ran locally.

## Testing Checklist 
Please delete options that are not relevant, and select all options that apply. 

- ✅ Existing Tests still pass
- ✅ Updated Existing Tests
- ✅ New Tests Added
- ✅ Ran locally on my machine

## Code Quality Checklist
Please delete options that are not relevant, and select all options that apply. 

- ✅ My code follows the guidelines of XYZ
- ✅ My code has been commented
- ✅ Documentation has been updated
- ✅ New and existing unit tests pass locally with my changes
- ✅ Main has been merged into this PR

2024-10-02 09:31 UTC, dbauszus-glx requested changes
![image](https://github.com/user-attachments/assets/30b1f1b8-ea10-4d31-97a2-ab78dc2401a0)

this looks a little squashed with the background.

should there be some distinction to the contents of a group?

2024-10-02 09:32 UTC, dbauszus-glx commented
Can you include some screenshots to show the before/after change?

2024-10-02 10:31 UTC, RobAndrewHurst commented
Can we create an issue for this? :)

2024-10-02 11:16 UTC, simon-leech commented
@RobAndrewHurst  Issue created here #1522

2024-10-04 10:24 UTC, simon-leech commented
![image](https://github.com/user-attachments/assets/962d9ae2-2550-45c5-bc21-fdad26414353)

Added some padding to the right so the arrow isn't squashed

2024-10-04 13:32 UTC, dbauszus-glx approved these changes
I have updated the padding to be for both sides instead of left and right defined seperately.

Should also be in em to adjust with text size.

Checked against dark mode and looking ok now.

![image](https://github.com/user-attachments/assets/b0981d10-6dd8-4662-b873-6069926f742e)

2024-10-04 13:33 UTC, merged