remove cloudinary provider module
GEOLYTIX/xyz pull request #1542
Opened 2024-10-08 14:27 UTC by dbauszus-glx

The cloudinary provide module has been effectively replaced by a sign module to sign cloudinary requests.

The cloudinary entries should use the sign method instead of the provider module which requires payloads to be passed through the XYZ host.

The cloudinary sign module must be documented.

2024-10-30 10:08 UTC, cityremade approved these changes
Works as expected.
I've replaced alerts and confirms with ui elements plus more human wording on removal confirm;

2024-10-31 08:25 UTC, RobAndrewHurst requested changes
![image](https://github.com/user-attachments/assets/8b938493-9713-459e-a75c-a5e593412041)

when removing a document that uses cloudinary the alert says I am going to remove an image which doesn't align with the action.

We should change this to something more fitting for documents

2024-10-31 08:32 UTC, RobAndrewHurst requested changes
![image](https://github.com/user-attachments/assets/770ed13d-9aee-4093-ba8f-1fc72fe7ed56)

All of these dictionary entries except the remove_item_confirm are not used anywhere in the core, and should be removed.

2024-10-31 08:33 UTC, RobAndrewHurst commented
> Works as expected. I've replaced alerts and confirms with ui elements plus more human wording on removal confirm;

This can't work with both images and documents.

2024-10-31 08:37 UTC, RobAndrewHurst commented on lib/ui/locations/entries/cloudinary.mjs
> +    alert(`Cloudinary document upload failed! ${errorDetail}`);
We will also want to make sure that all alerts are now using the core defined alerts in the module!
```suggestion
    alert(`Cloudinary document upload failed! ${errorDetail}`);
```mapp.ui.elements.alert();

2024-10-31 09:50 UTC, RobAndrewHurst approved these changes
I have have replaced the remove_item_confrim entry on the dictionary with two items. One for images and the other for documents.

They are then passed to the trash method as params.

2024-10-31 11:01 UTC, AlexanderGeere requested changes
Writing tests for the module

2024-10-31 13:49 UTC, AlexanderGeere approved these changes

2024-10-31 13:57 UTC, RobAndrewHurst approved these changes
Happy with this!

2024-10-31 13:59 UTC, merged