Input Elements: CSS changes
GEOLYTIX/xyz pull request #1552
Opened 2024-10-10 10:19 UTC by AlexanderGeere

## Description

Changes the css for input elements.
1. The input boxes above a slider now appear on either end of the slider elements thumbs.
2. Added a new parameter to slider_ab which lets the input element grow and shrink dynamically according the length of the value.
3. Input elements are now borderless except the bottom and have a slight grey background.
4. The Range editor will place the slider below the input box.
5. Added padding to the dialog element and to the content element of the dialog to avoid scrolling.
## GitHub Issue

[#1548](https://github.com/GEOLYTIX/xyz/issues/1548)

## Type of Change
- ✅ New feature (non-breaking change which adds functionality)

## How have you tested this? 
Tested using the multi_filter PR and any instance that has filters and editing.

## Testing Checklist 
- ✅ Existing Tests still pass
- ✅ Ran locally on my machine

## Code Quality Checklist
- ✅ My code follows the guidelines of XYZ
- ✅ My code has been commented
- ✅ Documentation has been updated
- ✅ New and existing unit tests pass locally with my changes
- ✅ Main has been merged into this PR

2024-10-10 15:31 UTC, dbauszus-glx commented
Do we need the light-off-black color? I can't really tell the difference between light-secondary and light-off-black.

![image](https://github.com/user-attachments/assets/072c1b42-3fea-4dbd-b7c6-b130fc7e3acc)

2024-10-10 16:18 UTC, dbauszus-glx approved these changes
https://github.com/GEOLYTIX/xyz/pull/1552/commits/f5d691b40d859b1035f1a7e68cd2f12bdeb17333

I set the text align to centre as the width is not perfect depending on the character widths.

I also removed --color-light-off-black to not use a colour once when there is another colour --color-light-secondary which looks almost the same.

The dialog content should not have additional padding by default causing a mis-alignment with the header. Padding to the content can be added with the content if a misalignment is the desired effect.

I added the position: fixed to the dropdown css. This seems to work like the absolute position hence there is no need to set this to absolute first and then to fixed in a dialog.

I removed the padding on label row as this is not required with the default style.

![image](https://github.com/user-attachments/assets/1b67461e-070c-42c3-b071-0550ec2f7e48)

2024-10-11 07:37 UTC, RobAndrewHurst approved these changes
Very Happy with this!

Nice @AlexanderGeere

2024-10-11 07:52 UTC, simon-leech requested changes
All working well for me! 

Just one question / comment - should we align the styling of textarea input with text and number? It stands out at the moment as different but the new styling is much cleaner so I would suggest we keep them all inline :)

![image](https://github.com/user-attachments/assets/291727ce-4038-4ffc-a1b5-cbe895768ff7)

2024-10-11 11:18 UTC, simon-leech approved these changes

2024-10-14 07:44 UTC, merged