Explain the WORKSPACE AGE in more detail
GEOLYTIX/xyz pull request #1628
Opened 2024-10-30 12:48 UTC by dbauszus-glx

The getTemplate and cacheWorkspace methods are now linked with an example and link to the query module why it is not recommended to set the WORKSPACE_AGE to 0.

2024-10-30 14:17 UTC, cityremade approved these changes

2024-10-30 15:11 UTC, AlexanderGeere approved these changes

2024-10-31 07:58 UTC, RobAndrewHurst requested changes
Do you think we should include a recommended workspace age in ms that a developer could use to with seeing local changes reflect quicker?

2024-10-31 08:59 UTC, dbauszus-glx commented
@RobAndrewHurst I wouldn't know a recommended value. The workspace age is only required if a workspace is likely to change. By default the workspace doesn't change hence there is no default age. I don't want to set this to an hour, or a day and then expkain that this is just an example default not required which can be overwritten.

2024-10-31 14:16 UTC, RobAndrewHurst approved these changes

2024-10-31 14:18 UTC, merged