CSV Upload
GEOLYTIX/xyz pull request #1642
Opened 2024-10-31 13:44 UTC by simon-leech

WILL POPULATE ONCE DONE - TBC - DON'T LOOK AT YET

# Pull Request Template

## Description

Please include a summary of the changes, and the motivation for the change.

## GitHub Issue

Provide the link to the relevant GitHub issue it addresses. 

## Type of Change
Please delete options that are not relevant, and select all options that apply. 

- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ New feature (non-breaking change which adds functionality)
- ✅ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- ✅ Documentation
- ✅ Testing

## How have you tested this? 
Please describe how to test this change and how you verified it worked. 

## Testing Checklist 
Please delete options that are not relevant, and select all options that apply. 

- ✅ Existing Tests still pass
- ✅ Updated Existing Tests
- ✅ New Tests Added
- ✅ Ran locally on my machine

## Code Quality Checklist
Please delete options that are not relevant, and select all options that apply. 

- ✅ My code follows the guidelines of XYZ
- ✅ My code has been commented
- ✅ Documentation has been updated
- ✅ New and existing unit tests pass locally with my changes
- ✅ Main has been merged into this PR

2024-11-05 14:15 UTC, AlexanderGeere requested changes
The upload button on the entry doesn't seem to get the id, when I attempt the upload the id is undefined, and nothing goes into the table. Side note it does say the import was successful.

2024-11-06 18:06 UTC, dbauszus-glx requested changes
This is way too complicated for general plugin / utility.

There is a situation where a very specific update query is executed from the resolution of multiple promises with insert quaeries which have to modules and must receive a body with an array property arr.

I would recommend to cleanup, test, and document POST queries with an array body first.

This is a valid select statement that will return to you the array sent as POST body.

```json
    "select_body": {
      "template": "SELECT %{body}",
      "value_only": true
    },
```

![image](https://github.com/user-attachments/assets/f244850d-c7c1-4522-b44d-af4aacb76cd4)

![image](https://github.com/user-attachments/assets/f10c8f79-3a80-47f5-9d4c-fc3d4ddadfb7)

Any rerences to the updateQuery should be removed from the csvUpload utility. These should be handled in the plugin which I would add in a seperate the PR.

The csvUpload utility should be in line with the csvDownload utility which merges multiple array responses into a CSV file.

The csvDownload method should be fully documented before another even more complex utility is added.

The specification for the csvUpload utility method should be to split a csv into seperate array bodies provided as POST body to a SQL query and return an array of responses from the individual queries once all queries are resolved. It must be possible to provide queryparams for the individual queries as well as a parameter for the payload to use in the array split. It should be possible to define whether all queries should be run in parallel or whether the queries should be sent consecutively.

This can be tested with very small csv file and providing a small enough payload param to force this csv to be split into at least two parts to be sent to the simple select %{body} statement which returns the body.

2025-01-13 14:11 UTC, RobAndrewHurst commented on lib/utils/csvUpload.mjs
> +      body: JSON.stringify({ arr: chunk }),
Testing!

2025-01-13 15:08 UTC, RobAndrewHurst commented
Test

2025-01-14 04:44 UTC, RobAndrewHurst commented on lib/utils/csvUpload.mjs
> +@property {Array} params.schema The schema array of column types.
Do we need to be so specific as to show an array? in docs?
What is the naming standard of these types. Is it 'function' or 'Function'. Is it 'string' or is it 'String'.

2025-01-14 04:44 UTC, RobAndrewHurst commented on lib/utils/csvUpload.mjs
> +@property {Array} params.schema The schema array of column types.
Do we need to be so specific as to show an array? in docs?
What is the naming standard of these types. Is it 'function' or 'Function'. Is it 'string' or is it 'String'.

2025-01-14 04:44 UTC, RobAndrewHurst commented on lib/utils/csvUpload.mjs
> +  const outcome = { success: true };
Should we not maybe want this to default to false. As that makes more sense from an error handling perspective.
It doesn't make sense to me that we start with a condition that we have successfully uploaded a csv.

2025-01-14 09:08 UTC, dbauszus-glx commented on lib/utils/csvUpload.mjs
> +@property {Array} params.schema The schema array of column types.
It doesn't really matter whether the type in capitals or not since we have been using either throughout.

2025-01-14 09:09 UTC, dbauszus-glx commented on lib/utils/csvUpload.mjs
> +  const outcome = { success: true };
I would like the logic with the outcome object to be changed but looking at this at the moment. Need to get a better understanding with some test cases which do not invlolve a plugin.

2025-01-14 12:32 UTC, RobAndrewHurst commented
Just putting this back into draft until @dbauszus-glx is ready with his changes.

2025-01-14 12:41 UTC, dbauszus-glx commented
> Just putting this back into draft until @dbauszus-glx is ready with his changes.

Thanks. I should have done this yesterday already.

2025-01-14 16:09 UTC, dbauszus-glx commented
I created a csv_upload utility for the json dataview to test the upload without the need for a plugin.

![image](https://github.com/user-attachments/assets/cef6878c-ba9a-4505-9d76-dc427fa214cb)

This dataview will simplly pump the rows into the select body query which returns the body from the post request to the sender.

```json
"dataviews": {
  "csv_json": {
    "display": true,
    "target": "tabview",
    "label": "Json",
    "dataview": "Json",
    "toolbar": {
      "jsonfile": true,
      "csvupload": {
        "header": true,
        "query": "select_body",
        "template": {
          "key": "select_body",
          "template": "SELECT %{body}",
          "value_only": true
        }
      }
    }
  }
}
```

I made a few changes to the csvUpload module.

The chunkSize is assigned to the params if nullish/undefined.

A check must be performed on the params.query prior to returning the Promise.

The headerCheck params property has been retired. If the header flag param is set then the file has a header.

The splitCSVIntoRow method has been renamed to splitRowIntoFields to indicate the purpose of the method.

The schemaMethods object is defined in the module, not inside the splitRowIntoFields method which doesn't require the params object.

'Text' is assumed as schema method for all fields if the schema params is undefined.

The processChunks method has been renamed to postRequestData as this method will post the data received and return the XHR utility method [promise].

The data chunks are pushed into the chunks array. The promises array is not required.

If async the chunks array will be mapped to return the XHR utility promises from the postRequestData method to the Promise.all() returning the indicidual responses.

If not async the chunks array will be iterated through in a for...of loop and the xhr from the postRequestData method will be awaited prior to the next chunk being loaded.

2025-01-14 16:12 UTC, dbauszus-glx requested changes
I feel there is a much simpler approach to splitting csv rows with a regex command. Iterating through each character feels inefficient.

2025-01-16 09:44 UTC, dbauszus-glx approved these changes
I am good with this but have written a lot of the logic. This must be tested by other people as well.

2025-01-16 10:15 UTC, dbauszus-glx commented
I think the CSV parser itself should be managed in a seperate ticket if needed. This is a lot more complex than I thought.

This is a good article why you shouldn't roll your own CSV parser. https://secretgeek.net/csv_trouble

I think in the future we should import a module like PapaParse for the job. https://github.com/mholt/PapaParse

2025-01-16 13:57 UTC, AlexanderGeere approved these changes
All working for me!

2025-01-16 15:51 UTC, RobAndrewHurst requested changes
Noticed some readability and complexity issues.

2025-01-16 15:51 UTC, RobAndrewHurst commented on lib/utils/csvUpload.mjs
> +  }
Do you think we should throw an error here rather than just return??

2025-01-16 15:51 UTC, RobAndrewHurst commented on lib/utils/csvUpload.mjs
> +      const rows = e.target.result.trim().split(/\r?\n/);
Could be a good idea to move this logic in the onload into its own function? Good for readability.

2025-01-16 15:51 UTC, RobAndrewHurst commented on lib/utils/csvUpload.mjs
> +
This is a bit difficult to read. Maybe we could break it up?

2025-01-16 15:51 UTC, RobAndrewHurst commented on lib/utils/csvUpload.mjs
> +    // Split row into fields array.
What does kbyte mean to us? Are we asking if this is in kilobytes? Or could it be?

2025-01-16 15:51 UTC, RobAndrewHurst commented on lib/utils/csvUpload.mjs
> +    if (chunkSize + rowSize >= params.chunkSize) {
Maybe we could break this up as it's also quite complex to read.

2025-01-16 17:46 UTC, RobAndrewHurst requested changes
I found some style changes and some complexity issues that we might want to address.

2025-01-16 17:46 UTC, RobAndrewHurst commented on lib/utils/csvUpload.mjs
> +    return;
Should we rather throw an error here instead of a return.

2025-01-16 17:46 UTC, RobAndrewHurst commented on lib/utils/csvUpload.mjs
> +  params.chunkSize ??= 1024 * 1024 * 4; //kbyte?
What does this mean to us?

2025-01-16 17:46 UTC, RobAndrewHurst commented on lib/utils/csvUpload.mjs
> +    reader.onload = async (e) => {
Maybe we should move this logic into it's own named function to help with readability.

2025-01-16 17:46 UTC, RobAndrewHurst commented on lib/utils/csvUpload.mjs
> +    const fieldsRow = `(${fields.map((v, i) => schemaMethods[params.schema?.[i] || 'Text'](v)).join()})`;
```suggestion
const schemaType = params.schema?.[i] || 'Text';
const convertedValue = schemaMethods[schemaType](v);
const fieldsRow = `(${convertedValue.join()})`;
```
This might want to be broken up to make it easier to read.

2025-01-16 17:46 UTC, RobAndrewHurst commented on lib/utils/csvUpload.mjs
> +        params.fields ??= headerRow.replaceAll('"', '').split(',');
This could also probably benefit from being broken up. Seems quite hard to read.

2025-01-16 17:46 UTC, RobAndrewHurst commented on lib/utils/csvUpload.mjs
> +  const qp = mapp.utils.queryParams(params);
```suggestion
  const queryParams = mapp.utils.queryParams(params);
```
I think we need a more obvious variable name here.

2025-01-16 18:23 UTC, dbauszus-glx commented on lib/utils/csvUpload.mjs
> +    return;
No. An error should be thrown if a method errs. Warning is for missing configuration.

2025-01-16 18:28 UTC, dbauszus-glx commented on lib/utils/csvUpload.mjs
> +        params.fields ??= headerRow.replaceAll('"', '').split(',');
Breaking up the replaceAll and the split method?

2025-01-16 18:37 UTC, RobAndrewHurst commented on lib/utils/csvUpload.mjs
> +        params.fields ??= headerRow.replaceAll('"', '').split(',');
Yeah! If we think it's 100% necessary :)

2025-01-16 18:46 UTC, dbauszus-glx commented on lib/utils/csvUpload.mjs
> +@property {Array} params.schema The schema array of column types.
If an array must be an array it should be defined as array type. If an array property could also be a different type of object then object is fine. The same goes for boolean which are also type Object.

2025-01-16 18:46 UTC, dbauszus-glx commented on lib/utils/csvUpload.mjs
> +  const outcome = { success: true };
This logic has been removed.

2025-01-16 18:55 UTC, dbauszus-glx commented on lib/utils/csvUpload.mjs
> +        params.fields ??= headerRow.replaceAll('"', '').split(',');
Like so?

```js
const headerRowWithOutDoubleQuotes = headerRow.replaceAll('"', '')
params.fields ??= headerRowWithOutDoubleQuotes.split(',');
```

2025-01-16 18:58 UTC, RobAndrewHurst commented on lib/utils/csvUpload.mjs
> +        params.fields ??= headerRow.replaceAll('"', '').split(',');
Sounds good!

2025-01-16 19:06 UTC, dbauszus-glx commented on lib/utils/csvUpload.mjs
> +        params.fields ??= headerRow.replaceAll('"', '').split(',');
I'd like a second opinion on this. Personally I feel the suggestion to verbose.

2025-01-17 09:02 UTC, RobAndrewHurst commented on lib/utils/csvUpload.mjs
> +        params.fields ??= headerRow.replaceAll('"', '').split(',');
It's just an option, but not necessary :)

2025-01-17 09:03 UTC, RobAndrewHurst approved these changes
All happy with this!

2025-01-17 09:03 UTC, merged