Test bundle
GEOLYTIX/xyz pull request #1707
Opened 2024-11-13 05:23 UTC by RobAndrewHurst

## Description

I have created a test bundle that will include assets such as workspaces that can be re-used in different environments. 

With this has come a big review of the tests.

The one thing I am struggling with is the run time of all the tests. I tried splitting up the tests into different promise batches that will all resolve at the same time. This however merge tests into different suites causing some confusion. 

Along side these changes comes a new codi 🐶 version v0.0.39 which has the option to only show the errors of the tests with the --quiet flag. 

This will be used in our other tests in other repos.

## GitHub Issue

#1440 

## Type of Change
Please delete options that are not relevant, and select all options that apply. 

- ✅ New feature (non-breaking change which adds functionality)
- ✅ Documentation
- ✅ Testing

2024-11-14 06:24 UTC, RobAndrewHurst commented on esbuild.config.mjs
> +    entryPoints: isDev ? ['./lib/mapp.mjs', './lib/ui.mjs'] : ['./lib/mapp.mjs', './lib/ui.mjs', './tests/_mapp.test.mjs'],
We bundle the test assets if we are in DEVELOPMENT mode. We can discuss if we want this all the time or in other certain situations.

2024-11-14 06:25 UTC, RobAndrewHurst commented on package.json
> +    "browser-sync": "npx browser-sync start --proxy localhost:3000 --port 3001 --ui-port 3002 --files public/js/**/* --no-open --no-notify",
Browser sync will now reload for either changes to lib or tests

2024-11-14 06:28 UTC, RobAndrewHurst commented on public/views/_test.html
> +                results = await codi.runWebTestFunction(_mappTest.coreTest);
This webTestFunction might be better used on each test function in the test bundle to try aid parallel testing in the future.

2024-11-14 06:29 UTC, RobAndrewHurst commented on tests/_mapp.test.mjs
> +self._mappTest = {
This is the test bundle entry point that self assigns just like mapp

2024-11-14 06:30 UTC, RobAndrewHurst commented on tests/assets/layers/cluster/layer.json
> +{
Example of saving away a configuration, which can be imported from the bundled test library.

2024-11-14 06:31 UTC, RobAndrewHurst commented on tests/lib/layer/format/mvt.test.mjs
> +import mvt_layer_default from '../../../assets/layers/mvt/layer.json';
Example of importing the asset. This will be applied more as I continue the re-review and structure of current tests

2024-11-14 06:32 UTC, RobAndrewHurst commented on tests/lib/mapview/allfeatures.test.mjs
> +    // await codi.describe('TODO: Mapview: allfeaturesTest', async () => {
Keeping these TODO's in the test base so I can get to the asap

2024-11-15 07:15 UTC, AlexanderGeere approved these changes
The quiet flag is a nice addition. The testing.md makes sense to me 👍

2024-11-15 09:23 UTC, simon-leech requested changes
The integrity tests are not working correctly. 

At the start of the integrity test it throws an error that /js/tests/_mapp.test.js does not exist (404). 

I also see an error 'Erroringrunning test file' using this path /public/tests/integrity.test.mjs. This is also timing out after 5000ms in the webRunner. 

The tests then also say that they have finished way before all the thematics have finished running through the test.

2024-11-15 09:40 UTC, dbauszus-glx submitted a review, later dismissed
The nodemon.json references local resources and must be added to ignore. The file and it's content must be referenced in the testing.md to explain the build process.

2024-11-15 11:35 UTC, RobAndrewHurst commented
> The nodemon.json references local resources and must be added to ignore. The file and it's content must be referenced in the testing.md to explain the build process.

I have updated the documentation and removed nodemon.json and added in an example config into the DEVELOPING docs

2024-11-15 12:22 UTC, RobAndrewHurst commented
After some discussion @simon-leech has pushed a change where the test bundle will happen all the time. This is fine because only on the _test.html view do we call the bundle!

2024-11-15 14:26 UTC, simon-leech approved these changes

2024-11-18 14:52 UTC, dbauszus-glx approved these changes

2024-11-18 15:21 UTC, merged