Layer dataviews target
GEOLYTIX/xyz pull request #1781
Opened 2024-12-20 14:28 UTC by dbauszus-glx

Layer dataviews should behave similar to location dataviews. It should be possible to create dataviews in the layer view dataviews panel without the need for a tabview.

The forEach iteration of dataview object entries wasn't very elegant.

The method will now use a for of loop of the dataview object entries.

The chkbox element generated by the mapp.ui.Dataview() method will be added to the contents array for the dataview drawer.

The for loop will continue if the tabview has been identified on a mobile.

The dataview.target will be added to the content array if no target is defined in the dataview entry. This is the same behaviour used for location view dataviews.

It should be possible in the future to add the content from any panel method without the drawer element to the layer view. https://github.com/GEOLYTIX/xyz/issues/1719

2024-12-20 14:35 UTC, simon-leech requested changes
This section in the `location/entries/dataview.mjs` is wrong. 
An entry does not (ever) have a class. So `entry.class` is undefined, resulting in a class for the entry of `location undefined`. Instead I think this should use entry.query or entry.key as the class name?
``` js
    // Dataview will be rendered into location view.
    entry.locationViewTarget = mapp.utils.html.node`
      <div class="${`location ${entry.class}`}">`
````

2024-12-20 14:51 UTC, dbauszus-glx commented
@simon-leech I am ok for you to ammend this PR. Is the location class even needed for the dataview target element? It should be assumed from the element being positioned inside the location view grid.

Can you also review this item? I didn't want to add this to the layer dataview logic as I don't think this is ever used. I believe this to be some legacy logic from ancient 'report' application views. I believe in modern view scripts the dataview is created by calling the dataview method directly rather than calling the infoj method.

```js
  // Dataview will be rendered into target identified by ID.
  if (typeof entry.target === 'string' && document.getElementById(entry.target)) {

    // Assign element by ID as target.
    entry.target = document.getElementById(entry.target)

    // Create and update the dataview.
    if (mapp.ui.Dataview(entry) instanceof Error) return;

    entry.update()

    return;
  }
```

2025-01-02 13:30 UTC, simon-leech commented
> This section in the `location/entries/dataview.mjs` is wrong. An entry does not (ever) have a class. So `entry.class` is undefined, resulting in a class for the entry of `location undefined`. Instead I think this should use entry.query or entry.key as the class name?
> 
> ```js
>     // Dataview will be rendered into location view.
>     entry.locationViewTarget = mapp.utils.html.node`
>       <div class="${`location ${entry.class}`}">`
> ```


I have addressed this in this PR #1786  - as part of a patch, which will subsequently be merged into this PR once approved.

2025-01-02 14:16 UTC, simon-leech commented
> @simon-leech I am ok for you to ammend this PR. Is the location class even needed for the dataview target element? It should be assumed from the element being positioned inside the location view grid.
> 
> Can you also review this item? I didn't want to add this to the layer dataview logic as I don't think this is ever used. I believe this to be some legacy logic from ancient 'report' application views. I believe in modern view scripts the dataview is created by calling the dataview method directly rather than calling the infoj method.
> 
> ```js
>   // Dataview will be rendered into target identified by ID.
>   if (typeof entry.target === 'string' && document.getElementById(entry.target)) {
> 
>     // Assign element by ID as target.
>     entry.target = document.getElementById(entry.target)
> 
>     // Create and update the dataview.
>     if (mapp.ui.Dataview(entry) instanceof Error) return;
> 
>     entry.update()
> 
>     return;
>   }
> ```

On the second part of this example - we actually do still use this sometimes. You are right it came from legacy but I think we should still support it or it will mean re-writes to all 'report' application views when upgrading? 
An example is like this, where we use a `skipEntry` dataview with a `target` to be rendered as follows: 
``` json
  {
      "skipEntry": true,
      "label": "Demographics",
      "type": "dataview",
      "target": "demographic-details",
      "query": "report_demogs",
      "table": {
        "placeholder": "No Demographics",
        "layout": "fitColumns",
        "columns": [
          {
            "title": "Field",
            "field": "field",
            "headerSort": false,
            "resizable": false
          },
          {
            "title": "Value",
            "field": "value",
            "headerSort": false,
            "resizable": false
          },
          {
            "title": "Field",
            "field": "field2",
            "headerSort": false,
            "resizable": false
          },
          {
            "title": "Value",
            "field": "value2",
            "headerSort": false,
            "resizable": false
          }
        ]
      }
    },
``` js
  // Create tableviews that are stored on the report layer
    location.infoj
      .filter((entry) =>
        new Set([
          "demographic-details",
        ]).has(entry.target)
      )
      .forEach((entry) =>
        mapp.ui.Dataview(entry).then((table) => table.update())
      );
```

2025-01-08 14:14 UTC, simon-leech commented
I put this into draft until we merge the other dataview PR as i think they'll be merge conflicts to resolve.

2025-01-16 11:15 UTC, dbauszus-glx commented
The show/hide methods in the dataview layer panel are only required for dataviews in tabviews. For dataviews in the layer panel itself the default dataview methods assigned by the dataview ui module should work as expected.

2025-01-17 12:06 UTC, dbauszus-glx commented on lib/ui/layers/panels/dataviews.mjs
> +    //dataview._target ??= dataview.target
No; I removed this.

2025-01-17 12:07 UTC, dbauszus-glx commented on lib/ui/layers/panels/dataviews.mjs
> +      if (mapp.utils.mobile()) return;
No; The idea of this PR is to have dataviews in the layer panel which is available on mobile. The tabview is not available on mobile hence the check must be in the condition for the tabview.

2025-01-17 13:53 UTC, RobAndrewHurst commented on lib/ui/layers/panels/dataviews.mjs
> +      if (mapp.utils.mobile()) return;
```js
````

2025-01-20 08:46 UTC, RobAndrewHurst commented on lib/ui/locations/entries/dataview.mjs
> +    entry.chkbox = ui.elements.chkbox({
I removed the mapp.ui reference as this needs to be split as that was the point of splitting the mapp & ui libraries. I noticed there are actually quite a few references to mapp.ui that we are going to want to fix.

2025-01-20 12:26 UTC, RobAndrewHurst approved these changes
I am all happy with this!

2025-01-20 14:41 UTC, AlexanderGeere approved these changes
Working as expected.

2025-01-22 08:51 UTC, simon-leech commented
On a zoom-restricted layer, if I have the dataview turned on in the `layer-panel` and then zoom out so the layer is turned off. 
The dataview is still visible but behind the disabled mask. 
Is this the expected behaviour? I would have expected that we would hide the dataview? The same way that if you have a dataview in the `tabview` - is it hidden when you zoom beyond the restrictions. 
![image](https://github.com/user-attachments/assets/84c690f4-09ff-43a2-9628-4d8ad94c3818)

2025-01-22 08:52 UTC, simon-leech requested changes
On a zoom-restricted layer, if I have the `dataview` turned on in the `layer-panel` and then zoom out so the layer is turned off.
The `dataview` is still visible but behind the disabled mask.
Is this the expected behaviour? I would have expected that we would hide the `dataview`?
This would align the behaviour with that for you when have a `dataview` in the `tabview` - is it hidden when you zoom beyond the restrictions.
![image](https://github.com/user-attachments/assets/f8e1ade6-6fb7-4cbb-b600-895a554657c8)

2025-01-23 10:56 UTC, dbauszus-glx commented
@simon-leech The drawer within the layer view should now be collapsed if the layer is out of zoom range.

2025-01-23 16:01 UTC, simon-leech approved these changes

2025-01-23 16:09 UTC, merged