Reduce mapview complexity
GEOLYTIX/xyz pull request #1783
Opened 2024-12-20 17:34 UTC by dbauszus-glx

The mapview decorator method is currently the most complex in the mapp library.

Items relating to the openlayers view should be handled in the viewConfig method which creates the mapview.view object which can be used as options argument for the ol.View constructor.

2025-01-02 13:38 UTC, simon-leech approved these changes
This is working as expected for me on existing instances. 
Tested using both MAPP 'standard' view and also in MAPP 'custom' views with mapviews attached and it is working as previously.

2025-01-06 17:19 UTC, cityremade approved these changes
I've tested on a custom view with multiple maps

2025-01-07 08:41 UTC, RobAndrewHurst requested changes
![image](https://github.com/user-attachments/assets/0886001d-589e-4858-abed-73067d2c574c)

The decorate function has a complexity of 18.

2025-01-07 10:52 UTC, simon-leech approved these changes
Tested again and working as expected on both default MAPP and also in a custom view with multiple mapviews associated

2025-01-07 11:03 UTC, RobAndrewHurst approved these changes
LGTM!

2025-01-07 11:04 UTC, merged