enable ni filter entry and filter meta
GEOLYTIX/xyz pull request #601
Opened 2023-02-07 15:49 UTC by dbauszus-glx

This PR enables to define a NI filter in addition to the IN filter.

In addition the filter meta will be added to the filter card underneath the title.

```
        {
            "title": "Retailer",
            "field": "retailer",
            "filter": {
                "meta": "Exclude from layer filter",
                "type": "ni",
                "ni": [
                    "ALDI",
                    "Lidl",
                    "Tesco"
                ]
            }
        },
```

2023-02-16 17:25 UTC, simon-leech requested changes
I've been testing this and can confirm it's working well, except one small thing. If you set up a NI Type with distinct:true, dropdown:true and a meta - you will see an error. This error is not seen if you provide the filters options, it's only seen when using distinct:true. 

` "filter": {
                                "type": "ni",
                                "meta":"META",
                                "distinct":true,
                                "dropdown":true
                            }`
![image](https://user-images.githubusercontent.com/56163132/219441351-43312960-c90b-49ce-8066-30aaff4796dc.png)

2023-02-16 18:16 UTC, dbauszus-glx commented
Good spot. I rename input to content and make sure that content is always an array prior to the unshift.

I also merged the main into this branch.

2023-02-17 08:07 UTC, simon-leech approved these changes
All working now - thanks! Happy to merge!

2023-02-17 09:06 UTC, eo-uk approved these changes

2023-02-17 09:43 UTC, merged