Fix for single geometries on a locations entry
GEOLYTIX/xyz pull request #692
Opened 2023-04-19 09:36 UTC by RobAndrewHurst

2023-04-19 10:00 UTC, dbauszus-glx requested changes
.count is undefined for an array of elements.

![image](https://user-images.githubusercontent.com/22201617/233040674-53b22abf-b1e1-497b-8b22-a0a5856644bf.png)

2023-04-19 13:01 UTC, RobAndrewHurst commented
> .count is undefined for an array of elements.
> 
> ![image](https://user-images.githubusercontent.com/22201617/233040674-53b22abf-b1e1-497b-8b22-a0a5856644bf.png)

Ah my mistake! Sorry about that! I have also though about some additional things with regards to this drawer! More to follow.

2023-05-02 05:57 UTC, RobAndrewHurst commented
This has been checked and ready for further review!

2023-05-02 13:43 UTC, dbauszus-glx approved these changes

2023-05-02 13:44 UTC, merged