Add a question mark icon when tooltip is provided
GEOLYTIX/xyz pull request #867
Opened 2023-08-09 13:28 UTC by simon-leech

I am aware that tooltip has been possible within the infoj configuration for a long while. 
However, I noticed that when you provide a tooltip, there is no visual cue for the user to let them know if they hover over a title, they can see additional information. 
This PR simply adds the question mark SVG already defined in the XYZ framework to the end of the title - as a visual cue for the user to hover to see additional information. 
I have also updated the docs to add tooltip. 

https://github.com/GEOLYTIX/xyz/wiki/Workspace-Configuration#tooltip

2023-08-09 13:32 UTC, RobAndrewHurst commented
The question mark feels too close to the title

2023-08-09 14:13 UTC, dbauszus-glx requested changes
I like it.

Can you change div for span.

html.node requires access to the node web api which isn't required for assembling a node.

uhtml is self closing. You can use html`<span>foo` instead of html`<span>foo</span>

Margins and sizing should be provided as em instead of percent to reflect the font size.

The height of the span should be controlled as line-height.

```js
      entry.node.append(mapp.utils.html.node`
        <div
          class="label"
          style="${`${entry.css_title || ''}`}"
          title="${entry.tooltip || null}">${entry.title}
          ${entry.tooltip ? mapp.utils.html`<span style="line-height: 1; margin-left: 0.4em;" class="mobile-display-none mask-icon question-mark">${entry.tooltip}`: ''}`)
```

![image](https://github.com/GEOLYTIX/xyz/assets/22201617/0e4b3030-7b44-4d25-b4d9-e661e2d69540)

I added a commit with proposed changes.

2023-08-10 08:40 UTC, RobAndrewHurst approved these changes

2023-08-10 08:44 UTC, dbauszus-glx approved these changes

2023-08-10 08:44 UTC, merged