Assign location style to layer type default style.
GEOLYTIX/xyz pull request #937
Opened 2023-09-26 14:40 UTC by dbauszus-glx

Without a default style the location.style will be assigned as default style.

This applies to the `vector_layer` and `mvt_clone` type entries.

The `location.style` is assigned in the listview.mjs `mapview.locations` setter proxy.

Assigning an svg type in the entry default style will allow to create coloured icons from the `layer.style` fill and strokeColor.

```json
"style": {
 "default": {
  "type": "dot"
 }
}
```

2023-09-27 07:28 UTC, simon-leech requested changes
I don't think these things are related but I'm seeing some issues with mvt_clone. 

- The `mvt_clone` is returning all data from the cloned layer, not just the data that is returned by the query. 
- Swapping styles of an `mvt_clone` layer returns an error in the console from dropdown.mjs,

2023-09-27 14:20 UTC, simon-leech commented
I think these issues are being addressed in other PRs - so i will approve the functionality in this one!

2023-09-27 14:21 UTC, simon-leech approved these changes

2023-10-02 09:14 UTC, RobAndrewHurst approved these changes

2023-10-02 09:14 UTC, merged