Numeric Entry Module Refactor
GEOLYTIX/xyz pull request #944
Opened 2023-10-02 15:36 UTC by RobAndrewHurst

2023-10-03 10:17 UTC, dbauszus-glx requested changes
The refactor looks good but there doesn't seem to be an obvious way to control the numeric decimal points. It should be possible to define the maximumFractionDigits in the entry.

2023-10-03 11:03 UTC, dbauszus-glx commented
What is the bug to test for?

2023-10-03 11:28 UTC, RobAndrewHurst commented
> What is the bug to test for?

I have just updated the Initial comment for this! Sorry I left it in draft until I got to writing what the problem was.

2023-10-03 12:31 UTC, simon-leech approved these changes
This is all working for me and fixes the bug. 

I've pushed a commit to add `entry.precision` which will be used for the number of decimal places, or will default to 2 for numeric types. 

Added to the config docs here too https://github.com/GEOLYTIX/xyz/wiki/Workspace-Configuration#numeric-1

2023-10-03 12:31 UTC, RobAndrewHurst commented
> This is all working for me and fixes the bug.
> 
> I've pushed a commit to add `entry.precision` which will be used for the number of decimal places, or will default to 2 for numeric types.
> 
> Added to the config docs here too https://github.com/GEOLYTIX/xyz/wiki/Workspace-Configuration#numeric-1

Nice one!!

2023-10-03 12:36 UTC, dbauszus-glx commented
@simon-leech Have a look at the use of toLocaleString with options as defined for the numbers in tabulator. A similar format should be used.

2023-10-03 13:31 UTC, simon-leech commented
@dbauszus-glx Amended this to use `toLocaleString` and `formatterParams` as per our Tabulator formatting. 

``` json 
  {
      "title": "X",
      "field": "field",
      "type": "numeric",
      "formatterParams": {
        "options": {
          "maximumFractionDigits": 5
        },
        "locale": "en-GB"
      },
      "inline": true,
      "prefix": "£"
    },
```

2023-10-04 10:01 UTC, dbauszus-glx approved these changes
looks good now. thanks for updating the wiki.

2023-10-04 10:01 UTC, merged