sqlfilter / json url parameter encoding
GEOLYTIX/xyz pull request #988
Opened 2023-10-30 18:09 UTC by dbauszus-glx

JSON does not want to be encoded as stringified URI. A JSON value may contain an ampersand (&) character. The JSON value should be stringified and URLComponent encoded.

The api module script should not be required to decode URI parameter. This should happen by default.

Hence the parameter value is already assumed to be encoded by the time the value is added to [filter] SQLParams array. The skip option for the wildcard is therefore unnecessary.

2023-10-31 13:08 UTC, simon-leech requested changes
@dbauszus-glx Thanks for this - been doing a little bit of testing. 
This is working for `filter.current` which contains a % or &. 
This is working for the legend filter which contains a % or &.

However, the filter module is not working correctly. It throws an error in the console 
![image](https://github.com/GEOLYTIX/xyz/assets/56163132/2f4869e2-99ba-4742-8b1f-77bf567f909f)

2023-11-01 10:05 UTC, simon-leech commented
@dbauszus-glx Just pushed a fix to this i think - but needs testing by others.

2023-11-01 11:26 UTC, simon-leech approved these changes
This is all working for me now !

2023-11-02 11:28 UTC, RobAndrewHurst approved these changes
Looks all good to me!

2023-11-02 13:15 UTC, simon-leech approved these changes

2023-11-02 13:20 UTC, merged